ATMega32 Drivers: vAPPS_main
vAPPS_main()
void vAPPS_main (void)
Definition at line 43 of file APPS_main.c.
{
#ifdef TESTING_GPIO
    vTestingGPIO();
#elif defined TESTING_EXTI
    vTestingEXTI();
#elif defined TESTING_ADC
    vTestingADC();
#elif defined TESTING_TIMER0DELAYSYNC
    vTestingTIMER0DelaySync();
#elif defined TESTING_TIMER1DELAYSYNC
    vTestingTIMER1DelaySync();
#elif defined TESTING_TIMER2DELAYSYNC
    vTestingTIMER2DelaySync();
#elif defined TESTING_TIMER0PWM
    vTestingTIMER0PWM();
#elif defined TESTING_TIMER1APWM
    vTestingTIMER1APWM();
#elif defined TESTING_TIMER1BPWM
    vTestingTIMER1BPWM();
#elif defined TESTING_TIMER2PWM
    vTestingTIMER2PWM();
#elif defined TESTING_ADCTIMER
    vTestingADCTIMER();
#elif defined TESTING_USARTGPIO
    vTestingUSARTGPIO();
#endif
    while (TRUE)
    {
    }
}
References TRUE, vTestingADC(), vTestingADCTIMER(), vTestingEXTI(), vTestingGPIO(), vTestingTIMER0DelaySync(), vTestingTIMER0PWM(), vTestingTIMER1APWM(), vTestingTIMER1BPWM(), vTestingTIMER1DelaySync(), vTestingTIMER2DelaySync(), vTestingTIMER2PWM(), and vTestingUSARTGPIO().