ATMega32 Drivers: MGPIO_vSetPinDirection
MGPIO_vSetPinDirection()
void MGPIO_vSetPinDirection (u8_t L_u8Port, u8_t L_u8Pin, u8_t L_u8Direction)
Apply a certain direction on a certain pin.
Parameters
[in] L_u8Port The port that the pin belongs to,
See also
GPIO Ports
Parameters
[in] L_u8Pin The pin to update its direction,
See also
GPIO Pins
Parameters
[in] L_u8Direction The direction to apply on the pin,
See also
GPIO Directions
Definition at line 15 of file GPIO_program.c.
{
    switch (L_u8Port)
    {
    case GPIO_PORTA:
        switch (L_u8Direction)
        {
        case INPUT_PULLUP:
            CLEAR_BIT(DDRA, L_u8Pin);
            SET_BIT(PORTA, L_u8Pin);
            break;
        case INPUT_PULLDOWN:
            CLEAR_BIT(DDRA, L_u8Pin);
            CLEAR_BIT(PORTA, L_u8Pin);
            break;
        case OUTPUT:
            SET_BIT(DDRA, L_u8Pin);
            break;
        }
        break;
    case GPIO_PORTB:
        switch (L_u8Direction)
        {
        case INPUT_PULLUP:
            CLEAR_BIT(DDRB, L_u8Pin);
            SET_BIT(PORTB, L_u8Pin);
            break;
        case INPUT_PULLDOWN:
            CLEAR_BIT(DDRB, L_u8Pin);
            CLEAR_BIT(PORTB, L_u8Pin);
            break;
        case OUTPUT:
            SET_BIT(DDRB, L_u8Pin);
            break;
        }
        break;
    case GPIO_PORTC:
        switch (L_u8Direction)
        {
        case INPUT_PULLUP:
            CLEAR_BIT(DDRC, L_u8Pin);
            SET_BIT(PORTC, L_u8Pin);
            break;
        case INPUT_PULLDOWN:
            CLEAR_BIT(DDRC, L_u8Pin);
            CLEAR_BIT(PORTC, L_u8Pin);
            break;
        case OUTPUT:
            SET_BIT(DDRC, L_u8Pin);
            break;
        }
        break;
    case GPIO_PORTD:
        switch (L_u8Direction)
        {
        case INPUT_PULLUP:
            CLEAR_BIT(DDRD, L_u8Pin);
            SET_BIT(PORTD, L_u8Pin);
            break;
        case INPUT_PULLDOWN:
            CLEAR_BIT(DDRD, L_u8Pin);
            CLEAR_BIT(PORTD, L_u8Pin);
            break;
        case OUTPUT:
            SET_BIT(DDRD, L_u8Pin);
            break;
        }
        break;
    }
}
References CLEAR_BIT, DDRA, DDRB, DDRC, DDRD, GPIO_PORTA, GPIO_PORTB, GPIO_PORTC, GPIO_PORTD, INPUT_PULLDOWN, INPUT_PULLUP, OUTPUT, PORTA, PORTB, PORTC, PORTD, and SET_BIT.
Referenced by vTestingADC(), vTestingEXTI(), vTestingGPIO(), vTestingTIMER0DelaySync(), vTestingTIMER0PWM(), vTestingTIMER1APWM(), vTestingTIMER1BPWM(), vTestingTIMER1DelaySync(), vTestingTIMER2DelaySync(), and vTestingTIMER2PWM().