ATMega32 Drivers: MTIMER_vOutputPhaseCorrectPWM
MTIMER_vOutputPhaseCorrectPWM()
void MTIMER_vOutputPhaseCorrectPWM (u8_t u8Channel, u8_t u8DutyCycle)
This function is used to output a PWM signal in Phase Correct PWM mode on a certain channel with a certain duty cycle.
Parameters
[in] u8Channel The Timer channel to be used
See also
Timer Channels
Parameters
[in] u8DutyCycle The duty cycle of the PWM signal (0-255)
Definition at line 504 of file TIMER_program.c.
{
    u8_t u8Prescaler = ((u8Channel == TIMER_CHANNEL_2) ? TIMER_CFG_PHASECORRECTPWM2_PRESCALER : TIMER_CFG_PHASECORRECTPWM01_PRESCALER);
    MTIMER_vInit(u8Channel, TIMER_MODE_PWM_PHASECORRECT);
    MTIMER_vSetInitialPWMValue(u8Channel, MTIMER_vAdjustDutyCycle(u8Channel, TIMER_MODE_PWM_PHASECORRECT, u8DutyCycle));
    MTIMER_vStartTimer(u8Channel, u8Prescaler);
}
References MTIMER_vAdjustDutyCycle(), MTIMER_vInit(), MTIMER_vSetInitialPWMValue(), MTIMER_vStartTimer(), TIMER_CFG_PHASECORRECTPWM01_PRESCALER, TIMER_CFG_PHASECORRECTPWM2_PRESCALER, TIMER_CHANNEL_2, and TIMER_MODE_PWM_PHASECORRECT.
Referenced by vTestingTIMER1APWM(), vTestingTIMER1BPWM(), and vTestingTIMER2PWM().