ATMega32 Drivers: MTIMER_vDelaySec
MTIMER_vDelaySec()
void MTIMER_vDelaySec (u8_t u8Channel, u32_t u32Delay)
This function is used to delay for a specific time in seconds (s)
Parameters
[in] u8Channel The Timer channel to be used
See also
Timer Channels
Parameters
[in] u32Delay The delay time in seconds (s)
Note
Use this function for delays >= 1s
Definition at line 447 of file TIMER_program.c.
{
    u8_t L_u8Prescaler = ((u8Channel == TIMER_CHANNEL_2) ? TIMER_PRESCALER_TIMER2_1024 : TIMER_PRESCALER_TIMER01_1024);
    MTIMER_vInit(u8Channel, TIMER_MODE_CTC);
    switch (u8Channel)
    {
    case TIMER_CHANNEL_0:
    case TIMER_CHANNEL_2:
        MTIMER_vSetInitialCTCModeValue(u8Channel, 125);
        for (u8_t u8LoopCounter = 0; u8LoopCounter < 125; u8LoopCounter++)
        {
            MTIMER_vStartTimerCTC(u8Channel, L_u8Prescaler, u32Delay);
        }
        break;
    case TIMER_CHANNEL_1A:
    case TIMER_CHANNEL_1B:
        MTIMER_vSetInitialCTCModeValue(TIMER_CHANNEL_1A, 15625);
        MTIMER_vStartTimerCTC(TIMER_CHANNEL_1A, L_u8Prescaler, u32Delay);
        break;
    default:
        break;
    }
    MTIMER_vStopTimer(u8Channel);
}
References MTIMER_vInit(), MTIMER_vSetInitialCTCModeValue(), MTIMER_vStartTimerCTC(), MTIMER_vStopTimer(), TIMER_CHANNEL_0, TIMER_CHANNEL_1A, TIMER_CHANNEL_1B, TIMER_CHANNEL_2, TIMER_MODE_CTC, TIMER_PRESCALER_TIMER01_1024, and TIMER_PRESCALER_TIMER2_1024.
Referenced by vTestingTIMER0DelaySync(), vTestingTIMER1DelaySync(), and vTestingTIMER2DelaySync().