ATMega32 Drivers: MTIMER_vStartTimerSync
MTIMER_vStartTimerSync()
static void MTIMER_vStartTimerSync (u8_t u8Channel, u8_t u8Prescaler, u32_t u32Delay) static
This function is used to start the timer in a synchronous mode (blocking)
Parameters
[in] u8Channel The Timer channel to be used
See also
Timer Channels
Parameters
[in] u8Prescaler The Timer prescaler to be used
See also
Timer Prescaler
Parameters
[in] u32Delay The delay
Definition at line 26 of file TIMER_program.c.
{
    switch (u8Channel)
    {
    case TIMER_CHANNEL_0:
        TCCR0 |= (u8Prescaler);
        while (u32Delay--)
        {
            while (!GET_BIT(TIFR, 1))
                ;
            SET_BIT(TIFR, 1);
        }
        break;
    case TIMER_CHANNEL_1:
        TCCR1 = 0;
        break;
    case TIMER_CHANNEL_2:
        TCCR2 |= (u8Prescaler);
        break;
    default:
        break;
    }
}
References GET_BIT, SET_BIT, TCCR0, TCCR1, TCCR2, TIFR, TIMER_CHANNEL_0, TIMER_CHANNEL_1, and TIMER_CHANNEL_2.
Referenced by MTIMER_vSyncDelay(), MTIMER_vSyncDelayMS(), MTIMER_vSyncDelayS(), and MTIMER_vSyncDelayUS().