ATMega32 Drivers: MTIMER_vStartTimer
MTIMER_vStartTimer()
static void MTIMER_vStartTimer (u8_t u8Channel, u8_t u8Prescaler) static
Start the timer with a specific prescaler.
Parameters
[in] u8Channel The channel to be used for the PWM modes
[in] u8Prescaler The prescaler to be used for the PWM modes
Definition at line 105 of file TIMER_program.c.
{
    switch (u8Channel)
    {
    case TIMER_CHANNEL_0:
        TCCR0 |= (u8Prescaler);
        break;
    case TIMER_CHANNEL_1A:
    case TIMER_CHANNEL_1B:
        TCCR1B |= (u8Prescaler);
        break;
    case TIMER_CHANNEL_2:
        TCCR2 |= (u8Prescaler);
        break;
    default:
        break;
    }
}
References TCCR0, TCCR1B, TCCR2, TIMER_CHANNEL_0, TIMER_CHANNEL_1A, TIMER_CHANNEL_1B, and TIMER_CHANNEL_2.
Referenced by MTIMER_vOutputFastPWM(), MTIMER_vOutputPhaseCorrectPWM(), MTIMER_vStartTimerCTC(), and MTIMER_vStartTimerNormal().