ATMega32 Drivers: MTIMER_vInit
MTIMER_vInit()
static void MTIMER_vInit (u8_t u8Channel, u8_t u8Mode) static
This function is used to initiate the timer with a certain mode.
Parameters
[in] u8Channel The Timer channel to be used
See also
Timer Channels
Parameters
[in] u8Mode The Timer mode to be used
See also
Timer Modes
Definition at line 203 of file TIMER_program.c.
{
    MTIMER_vStopTimer(u8Channel);
    switch (u8Channel)
    {
    case TIMER_CHANNEL_0:
        switch (u8Mode)
        {
        case TIMER_MODE_NORMAL:
            TCCR0 = TIMER_MODE_NORMAL;
            SET_BIT(TIMSK, TIMSK_TOIE2);
            break;
        case TIMER_MODE_CTC:
            TCCR0 = (TIMER_CFG_TIMER0_CTC_PORT_OUTPUT_MODE | TIMER_MODE_CTC);
            SET_BIT(TIMSK, TIMSK_OCIE0);
            break;
        case TIMER_MODE_PWM_FAST:
            TCCR0 = (TIMER_CFG_TIMER0_FASTPWM_PORT_OUTPUT_MODE | TIMER_MODE_PWM_FAST);
            break;
        case TIMER_MODE_PWM_PHASECORRECT:
            TCCR0 = (TIMER_CFG_TIMER0_PHASECORRECTPWM_PORT_OUTPUT_MODE | TIMER_MODE_PWM_PHASECORRECT);
            break;
        default:
            break;
        }
        break;
    case TIMER_CHANNEL_1A:
    case TIMER_CHANNEL_1B:
        switch (u8Mode)
        {
        case TIMER_MODE_NORMAL:
            TCCR1A = 0;
            TCCR1B = 0;
            SET_BIT(TIMSK, TIMSK_TOIE1);
            break;
        case TIMER_MODE_CTC:
            TCCR1A = (((u8Channel == TIMER_CHANNEL_1A) ? TIMER_CFG_TIMER1A_CTC_PORT_OUTPUT_MODE : TIMER_CFG_TIMER1B_CTC_PORT_OUTPUT_MODE) | 0);
            TCCR1B = 0x08;
            SET_BIT(TIMSK, ((u8Channel == TIMER_CHANNEL_1A) ? TIMSK_OCIE1A : TIMSK_OCIE1B));
            break;
        case TIMER_MODE_PWM_FAST:
            TCCR1A = (((u8Channel == TIMER_CHANNEL_1A) ? TIMER_CFG_TIMER1A_FASTPWM_PORT_OUTPUT_MODE : TIMER_CFG_TIMER1B_FASTPWM_PORT_OUTPUT_MODE) | 0x01);
            TCCR1B = 0x08;
            break;
        case TIMER_MODE_PWM_PHASECORRECT:
            TCCR1A = (((u8Channel == TIMER_CHANNEL_1A) ? TIMER_CFG_TIMER1A_PHASECORRECTPWM_PORT_OUTPUT_MODE : TIMER_CFG_TIMER1B_PHASECORRECTPWM_PORT_OUTPUT_MODE) | 0x01);
            TCCR1B = 0;
            break;
        default:
            break;
        }
        break;
    case TIMER_CHANNEL_2:
        switch (u8Mode)
        {
        case TIMER_MODE_NORMAL:
            TCCR2 = TIMER_MODE_NORMAL;
            SET_BIT(TIMSK, TIMSK_TOIE2);
            break;
        case TIMER_MODE_CTC:
            TCCR2 = (TIMER_CFG_TIMER2_CTC_PORT_OUTPUT_MODE | TIMER_MODE_CTC);
            SET_BIT(TIMSK, TIMSK_OCIE2);
            break;
        case TIMER_MODE_PWM_FAST:
            TCCR2 = (TIMER_CFG_TIMER2_FASTPWM_PORT_OUTPUT_MODE | TIMER_MODE_PWM_FAST);
            break;
        case TIMER_MODE_PWM_PHASECORRECT:
            TCCR2 = (TIMER_CFG_TIMER2_PHASECORRECTPWM_PORT_OUTPUT_MODE | TIMER_MODE_PWM_PHASECORRECT);
            break;
        default:
            break;
        }
        break;
    default:
        break;
    }
}
References MTIMER_vStopTimer(), SET_BIT, TCCR0, TCCR1A, TCCR1B, TCCR2, TIMER_CFG_TIMER0_CTC_PORT_OUTPUT_MODE, TIMER_CFG_TIMER0_FASTPWM_PORT_OUTPUT_MODE, TIMER_CFG_TIMER0_PHASECORRECTPWM_PORT_OUTPUT_MODE, TIMER_CFG_TIMER1A_CTC_PORT_OUTPUT_MODE, TIMER_CFG_TIMER1A_FASTPWM_PORT_OUTPUT_MODE, TIMER_CFG_TIMER1A_PHASECORRECTPWM_PORT_OUTPUT_MODE, TIMER_CFG_TIMER1B_CTC_PORT_OUTPUT_MODE, TIMER_CFG_TIMER1B_FASTPWM_PORT_OUTPUT_MODE, TIMER_CFG_TIMER1B_PHASECORRECTPWM_PORT_OUTPUT_MODE, TIMER_CFG_TIMER2_CTC_PORT_OUTPUT_MODE, TIMER_CFG_TIMER2_FASTPWM_PORT_OUTPUT_MODE, TIMER_CFG_TIMER2_PHASECORRECTPWM_PORT_OUTPUT_MODE, TIMER_CHANNEL_0, TIMER_CHANNEL_1A, TIMER_CHANNEL_1B, TIMER_CHANNEL_2, TIMER_MODE_CTC, TIMER_MODE_NORMAL, TIMER_MODE_PWM_FAST, TIMER_MODE_PWM_PHASECORRECT, TIMSK, TIMSK_OCIE0, TIMSK_OCIE1A, TIMSK_OCIE1B, TIMSK_OCIE2, TIMSK_TOIE1, and TIMSK_TOIE2.
Referenced by MTIMER_vDelay(), MTIMER_vDelayMS(), MTIMER_vDelaySec(), MTIMER_vDelayUS(), MTIMER_vOutputFastPWM(), and MTIMER_vOutputPhaseCorrectPWM().