ATMega32 Drivers: MTIMER_vDelay
MTIMER_vDelay()
void MTIMER_vDelay (u8_t u8Channel, u8_t u8Mode, u8_t u8Prescaler, u16_t u16InitalValue, u32_t u32Delay)
This is a more of a generic function to delay for a specific time.
Parameters
[in] u8Channel The Timer channel to be used
See also
Timer Channels
Parameters
[in] u8Mode The Timer mode to be used
See also
Timer Modes
Parameters
[in] u8Prescaler The Timer prescaler to be used
See also
timer_prescaler
Parameters
[in] u16InitalValue The initial value of the timer
[in] u32Delay The number of ticks to be counted
Note
When using this function in normal mode, the u16InitalValue is ignored and the timer is started from 0 instead
When using this function in CTC mode, the u16InitalValue is used as the compare value
Definition at line 475 of file TIMER_program.c.
{
    MTIMER_vInit(u8Channel, u8Mode);
    switch (u8Mode)
    {
    case TIMER_MODE_NORMAL:
        MTIMER_vSetInitialNormalModeValue(u8Channel, u32Delay);
        MTIMER_vStartTimerNormal(u8Channel, u8Prescaler);
        break;
    case TIMER_MODE_CTC:
        MTIMER_vSetInitialCTCModeValue(u8Channel, u16InitalValue);
        MTIMER_vStartTimerCTC(u8Channel, u8Prescaler, u32Delay);
        break;
    default:
        break;
    }
    MTIMER_vStopTimer(u8Channel);
}
References MTIMER_vInit(), MTIMER_vSetInitialCTCModeValue(), MTIMER_vSetInitialNormalModeValue(), MTIMER_vStartTimerCTC(), MTIMER_vStartTimerNormal(), MTIMER_vStopTimer(), TIMER_MODE_CTC, and TIMER_MODE_NORMAL.