ATMega32 Drivers: MTIMER_vInit
MTIMER_vInit()
static void MTIMER_vInit (u8_t u8Channel, u8_t u8Mode, bool_t bIsSync) static
Definition at line 75 of file TIMER_program.c.
{
    MTIMER_vStopTimer(u8Channel);
    switch (u8Channel)
    {
    case TIMER_CHANNEL_0:
        TCCR0 = u8Mode;
        TCNT0 = 0;
        if (bIsSync)
        {
            SET_BIT(TIMSK, 1);
        }
        else
        {
            CLEAR_BIT(TIMSK, 1);
        }
        break;
    case TIMER_CHANNEL_1:
        break;
    case TIMER_CHANNEL_2:
        break;
    default:
        break;
    }
}
References CLEAR_BIT, MTIMER_vStopTimer(), SET_BIT, TCCR0, TCNT0, TIMER_CHANNEL_0, TIMER_CHANNEL_1, TIMER_CHANNEL_2, and TIMSK.
Referenced by MTIMER_vSyncDelay(), MTIMER_vSyncDelayMS(), MTIMER_vSyncDelayS(), and MTIMER_vSyncDelayUS().