ATMega32 Drivers: MTIMER_vStop
MTIMER_vStop()
void MTIMER_vStop (u8_t u8Channel)
This function is used to stop the timer on a certain channel.
Parameters
[in] u8Channel The Timer channel to be used
See also
Timer Channels
Definition at line 75 of file TIMER_program.c.
{
    switch (u8Channel)
    {
    case TIMER_CHANNEL_0:
        TCCR0 = 0;
        break;
    case TIMER_CHANNEL_1:
        TCCR1 = 0;
        break;
    case TIMER_CHANNEL_2:
        TCCR2 = 0;
        break;
    default:
        break;
    }
}
References TCCR0, TCCR1, TCCR2, TIMER_CHANNEL_0, TIMER_CHANNEL_1, and TIMER_CHANNEL_2.
Referenced by MTIMER_vInit(), MTIMER_vSyncDelay(), MTIMER_vSyncDelayMS(), MTIMER_vSyncDelayS(), and MTIMER_vSyncDelayUS().