ATMega32 Drivers: MTIMER_vSetInitialPWMValue
MTIMER_vSetInitialPWMValue()
static void MTIMER_vSetInitialPWMValue (u8_t u8Channel, u8_t u8DutyCycle) static
Set the initial value for the PWM modes.
Parameters
[in] u8Channel The channel to be used for the PWM modes
[in] u8DutyCycle The duty cycle to be used for the PWM modes
Note
This function should be used only in PWM modes (Fast PWM, Phase Correct PWM)
Definition at line 77 of file TIMER_program.c.
{
    MTIMER_vSetInitialNormalModeValue(u8Channel, 0);
    switch (u8Channel)
    {
    case TIMER_CHANNEL_0:
        OCR0 = u8DutyCycle;
        break;
    case TIMER_CHANNEL_1A:
        OCR1A = u8DutyCycle;
        break;
    case TIMER_CHANNEL_1B:
        OCR1B = u8DutyCycle;
        break;
    case TIMER_CHANNEL_2:
        OCR2 = u8DutyCycle;
        break;
    default:
        break;
    }
}
References MTIMER_vSetInitialNormalModeValue(), OCR0, OCR1A, OCR1B, OCR2, TIMER_CHANNEL_0, TIMER_CHANNEL_1A, TIMER_CHANNEL_1B, and TIMER_CHANNEL_2.
Referenced by MTIMER_vOutputFastPWM(), and MTIMER_vOutputPhaseCorrectPWM().