ATMega32 Drivers: MTIMER_vStopTimer
MTIMER_vStopTimer()
void MTIMER_vStopTimer (u8_t u8Channel)
This function is used to stop the timer on a certain channel.
Parameters
[in] u8Channel The Timer channel to be used
See also
Timer Channels
Definition at line 409 of file TIMER_program.c.
{
    switch (u8Channel)
    {
    case TIMER_CHANNEL_0:
        TCCR0 = 0;
        break;
    case TIMER_CHANNEL_1A:
    case TIMER_CHANNEL_1B:
        TCCR1A = 0;
        TCCR1B = 0;
        break;
    case TIMER_CHANNEL_2:
        TCCR2 = 0;
        break;
    default:
        break;
    }
}
References TCCR0, TCCR1A, TCCR1B, TCCR2, TIMER_CHANNEL_0, TIMER_CHANNEL_1A, TIMER_CHANNEL_1B, and TIMER_CHANNEL_2.
Referenced by MTIMER_vDelay(), MTIMER_vDelayMS(), MTIMER_vDelaySec(), MTIMER_vDelayUS(), and MTIMER_vInit().