ATMega32 Drivers: MTIMER_vSyncDelayS
MTIMER_vSyncDelayS()
void MTIMER_vSyncDelayS (u8_t u8Channel, u32_t u32Delay)
This function is used to delay for a specific time in seconds (s)
Parameters
[in] u8Channel The Timer channel to be used
See also
Timer Channels
Parameters
[in] u32Delay The delay time in seconds (s)
Note
Use this function for delays >= 1s
Definition at line 207 of file TIMER_program.c.
{
    u8_t L_u8Prescaler = ((u8Channel == TIMER_CHANNEL_2) ? TIMER_PRESCALER_TIMER2_1024 : TIMER_PRESCALER_TIMER01_1024);
    MTIMER_vInit(u8Channel, TIMER_MODE_CTC, TRUE);
    if ((u8Channel == TIMER_CHANNEL_1A) || (u8Channel == TIMER_CHANNEL_1B))
    {
        MTIMER_vSetInitialCTCModeValue(TIMER_CHANNEL_1A, 15625);
        MTIMER_vStartTimerCTCSync(TIMER_CHANNEL_1A, L_u8Prescaler, u32Delay);
    }
    else if ((u8Channel == TIMER_CHANNEL_0) || (u8Channel == TIMER_CHANNEL_2))
    {
        MTIMER_vSetInitialCTCModeValue(u8Channel, 125);
        for (u8_t u8LoopCounter = 0; u8LoopCounter < 125; u8LoopCounter++)
        {
            MTIMER_vStartTimerCTCSync(u8Channel, L_u8Prescaler, u32Delay);
        }
    }
    else
    {
        /* Do nothing */
    }
    MTIMER_vStopTimer(u8Channel);
}
References MTIMER_vInit(), MTIMER_vStartTimerCTCSync(), MTIMER_vStopTimer(), TIMER_CHANNEL_0, TIMER_CHANNEL_1A, TIMER_CHANNEL_1B, TIMER_CHANNEL_2, TIMER_MODE_CTC, TIMER_PRESCALER_TIMER01_1024, TIMER_PRESCALER_TIMER2_1024, and TRUE.