ATMega32 Drivers: MTIMER_vSetInitialNormalModeValue
MTIMER_vSetInitialNormalModeValue()
static void MTIMER_vSetInitialNormalModeValue (u8_t u8Channel, u16_t u16InitialValue) static
This function is used to set the initial value of TCNTn register in normal mode.
Parameters
[in] u8Channel The Timer channel to be used
See also
Timer Channels
Parameters
[in] u16InitialValue The initial value to be set in the TCNTn register
Note
This function should be used only in normal mode
Definition at line 25 of file TIMER_program.c.
{
    switch (u8Channel)
    {
    case TIMER_CHANNEL_0:
        TCNT0 = u16InitialValue;
        break;
    case TIMER_CHANNEL_1A:
    case TIMER_CHANNEL_1B:
        TCNT1 = u16InitialValue;
        break;
    case TIMER_CHANNEL_2:
        TCNT2 = u16InitialValue;
        break;
    default:
        break;
    }
}
References TCNT0, TCNT1, TCNT2, TIMER_CHANNEL_0, TIMER_CHANNEL_1A, TIMER_CHANNEL_1B, and TIMER_CHANNEL_2.
Referenced by MTIMER_vDelay(), MTIMER_vSetInitialCTCModeValue(), and MTIMER_vSetInitialPWMValue().