ATMega32 Drivers: MTIMER_vDelayUS
MTIMER_vDelayUS()
void MTIMER_vDelayUS (u8_t u8Channel, u32_t u32Delay)
This function is used to delay for a specific time in microseconds (us)
Parameters
[in] u8Channel The Timer channel to be used
See also
Timer Channels
Parameters
[in] u32Delay The delay time in microseconds (us)
Note
Use this function for delays < 1ms
Definition at line 429 of file TIMER_program.c.
{
    u8_t L_u8Prescaler = ((u8Channel == TIMER_CHANNEL_2) ? TIMER_PRESCALER_TIMER2_8 : TIMER_PRESCALER_TIMER01_8);
    MTIMER_vInit(u8Channel, TIMER_MODE_CTC);
    MTIMER_vSetInitialCTCModeValue(u8Channel, 2);
    MTIMER_vStartTimerCTC(u8Channel, L_u8Prescaler, u32Delay);
    MTIMER_vStopTimer(u8Channel);
}
References MTIMER_vInit(), MTIMER_vSetInitialCTCModeValue(), MTIMER_vStartTimerCTC(), MTIMER_vStopTimer(), TIMER_CHANNEL_2, TIMER_MODE_CTC, TIMER_PRESCALER_TIMER01_8, and TIMER_PRESCALER_TIMER2_8.