ATMega32 Drivers: vToggleLed
vToggleLed()
void vToggleLed (void)
Definition at line 15 of file TestingEXTI_main.c.
{
    MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN2, HIGH);
    MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN7, HIGH);
    MGPIO_vSetPinValue(GPIO_PORTD, GPIO_PIN3, HIGH);
    MEXTI_vDisableExternalInterrupt(EXTI_PIN_INT0);
}
References EXTI_PIN_INT0, GPIO_PIN2, GPIO_PIN3, GPIO_PIN7, GPIO_PORTC, GPIO_PORTD, HIGH, MEXTI_vDisableExternalInterrupt(), and MGPIO_vSetPinValue().
Referenced by vTestingEXTI().