ATMega32 Drivers: vTestingTIMER2DelaySync
vTestingTIMER2DelaySync()
void vTestingTIMER2DelaySync (void)
Definition at line 16 of file TestingTIMER2DelaySync_main.c.
{
    MGPIO_vSetPinDirection(GPIO_PORTC, GPIO_PIN2, OUTPUT);
    MGPIO_vSetPinDirection(GPIO_PORTC, GPIO_PIN7, OUTPUT);
    while (TRUE)
    {
        MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN2, HIGH);
        MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN7, LOW);
        MTIMER_vDelayMS(TIMER_CHANNEL_2, 5000);
        MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN2, LOW);
        MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN7, HIGH);
        MTIMER_vDelaySec(TIMER_CHANNEL_2, 5);
    }
}
References GPIO_PIN2, GPIO_PIN7, GPIO_PORTC, HIGH, LOW, MGPIO_vSetPinDirection(), MGPIO_vSetPinValue(), MTIMER_vDelayMS(), MTIMER_vDelaySec(), OUTPUT, TIMER_CHANNEL_2, and TRUE.
Referenced by vAPPS_main().