ATMega32 Drivers: vTestingADC
vTestingADC()
void vTestingADC (void)
Definition at line 16 of file TestingADC_main.c.
{
    u16_t L_u16Result = 0;
    MGPIO_vSetPinDirection(GPIO_PORTA, GPIO_PIN1, INPUT_PULLDOWN);
    MGPIO_vSetPinDirection(GPIO_PORTD, GPIO_PIN3, OUTPUT);
    MGPIO_vSetPinDirection(GPIO_PORTC, GPIO_PIN2, OUTPUT);
    MGPIO_vSetPinDirection(GPIO_PORTC, GPIO_PIN7, OUTPUT);
    MADC_vInit();
    while (TRUE)
    {
        L_u16Result = MADC_u16ReadChannel(ADC_CHANNEL_1);
        if (L_u16Result >= 250 && L_u16Result < 600)
        {
            MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN2, LOW);
            MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN7, HIGH);
            MGPIO_vSetPinValue(GPIO_PORTD, GPIO_PIN3, LOW);
        }
        else if (L_u16Result >= 600 && L_u16Result < 1024)
        {
            MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN2, LOW);
            MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN7, LOW);
            MGPIO_vSetPinValue(GPIO_PORTD, GPIO_PIN3, HIGH);
        }
        else
        {
            MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN2, HIGH);
            MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN7, LOW);
            MGPIO_vSetPinValue(GPIO_PORTD, GPIO_PIN3, LOW);
        }
    }
}
References ADC_CHANNEL_1, GPIO_PIN1, GPIO_PIN2, GPIO_PIN3, GPIO_PIN7, GPIO_PORTA, GPIO_PORTC, GPIO_PORTD, HIGH, INPUT_PULLDOWN, LOW, MADC_u16ReadChannel(), MADC_vInit(), MGPIO_vSetPinDirection(), MGPIO_vSetPinValue(), OUTPUT, and TRUE.
Referenced by vAPPS_main().