ATMega32 Drivers: vTestingEXTI
vTestingEXTI()
void vTestingEXTI (void)
Definition at line 23 of file TestingEXTI_main.c.
{
    MGPIO_vSetPinDirection(GPIO_PORTD, GPIO_PIN2, INPUT_PULLUP);
    MGPIO_vSetPinDirection(GPIO_PORTC, GPIO_PIN2, OUTPUT);
    MGPIO_vSetPinDirection(GPIO_PORTC, GPIO_PIN7, OUTPUT);
    MGPIO_vSetPinDirection(GPIO_PORTD, GPIO_PIN3, OUTPUT);
    MEXTI_vEnableExternalInterrupt(EXTI_PIN_INT0, EXTI_MODES_FALLING_EDGE, vToggleLed);
    while (TRUE)
    {
        MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN2, LOW);
        MGPIO_vSetPinValue(GPIO_PORTC, GPIO_PIN7, LOW);
        MGPIO_vSetPinValue(GPIO_PORTD, GPIO_PIN3, LOW);
    }
}
References EXTI_MODES_FALLING_EDGE, EXTI_PIN_INT0, GPIO_PIN2, GPIO_PIN3, GPIO_PIN7, GPIO_PORTC, GPIO_PORTD, INPUT_PULLUP, LOW, MEXTI_vEnableExternalInterrupt(), MGPIO_vSetPinDirection(), MGPIO_vSetPinValue(), OUTPUT, TRUE, and vToggleLed().
Referenced by vAPPS_main().