ATMega32 Drivers: vTestingTIMER1APWM
vTestingTIMER1APWM()
void vTestingTIMER1APWM (void)
Definition at line 16 of file TestingTIMER1APWM_main.c.
{
    u8_t counter = 0;
    u8_t fadeAmount = 5;
    MGPIO_vSetPinDirection(GPIO_PORTD, GPIO_PIN5, OUTPUT);
    while (TRUE)
    {
        counter += fadeAmount;
        if (counter <= 0 || counter >= 255)
        {
            fadeAmount = -fadeAmount;
        }
        // MTIMER_vOutputFastPWM(TIMER_CHANNEL_1A, counter);
        MTIMER_vOutputPhaseCorrectPWM(TIMER_CHANNEL_1A, counter);
        MTIMER_vDelayMS(TIMER_CHANNEL_2, 50);
    }
}
References GPIO_PIN5, GPIO_PORTD, MGPIO_vSetPinDirection(), MTIMER_vDelayMS(), MTIMER_vOutputPhaseCorrectPWM(), OUTPUT, TIMER_CHANNEL_1A, TIMER_CHANNEL_2, and TRUE.
Referenced by vAPPS_main().