ATMega32 Drivers: vTestingUSARTGPIO
vTestingUSARTGPIO()
void vTestingUSARTGPIO (void)
Definition at line 36 of file TestingUSARTGPIO_main.c.
{
    u8_t u8ReceivedData = 0;
    MGPIO_vSetPinDirection(GPIO_PORTD, GPIO_PIN0, INPUT_PULLDOWN);
    MGPIO_vSetPinDirection(GPIO_PORTD, GPIO_PIN1, OUTPUT);
    MGPIO_vSetPinDirection(GPIO_PORTD, GPIO_PIN3, OUTPUT);
    MUSART_vInit();
    while (TRUE)
    {
        MUSART_vAsyncTransmitData('B', vTurnonLed);
        MUSART_vAsyncReceiveData(vControlReceivedData);
        MGPIO_vSetPinValue(GPIO_PORTD, GPIO_PIN3, LOW);
        // MUSART_vSyncTransmitData('A');
        // MGPIO_vSetPinValue(GPIO_PORTD, GPIO_PIN3, LOW);
        // MTIMER_vDelayMS(TIMER_CHANNEL_0, 500);
        // MUSART_vSyncReceiveData((u16_t *)&u8ReceivedData);
        // if (u8ReceivedData == 'A')
        // {
        //     MGPIO_vSetPinValue(GPIO_PORTD, GPIO_PIN3, HIGH);
        // }
        // else
        // {
        //     MGPIO_vSetPinValue(GPIO_PORTD, GPIO_PIN3, LOW);
        // }
        MTIMER_vDelaySec(TIMER_CHANNEL_0, 1);
        u8ReceivedData = 0;
    }
}
References GPIO_PIN0, GPIO_PIN1, GPIO_PIN3, GPIO_PORTD, INPUT_PULLDOWN, LOW, MGPIO_vSetPinDirection(), MGPIO_vSetPinValue(), MTIMER_vDelaySec(), MUSART_vAsyncReceiveData(), MUSART_vAsyncTransmitData(), MUSART_vInit(), OUTPUT, TIMER_CHANNEL_0, TRUE, vControlReceivedData(), and vTurnonLed().
Referenced by vAPPS_main().