ATMega32 Drivers: vTestingTIMER0PWM
vTestingTIMER0PWM()
void vTestingTIMER0PWM (void)
Definition at line 16 of file TestingTIMER0PWM_main.c.
{
    u8_t counter = 0;
    u8_t fadeAmount = 5;
    MGPIO_vSetPinDirection(GPIO_PORTB, GPIO_PIN3, OUTPUT);
    while (TRUE)
    {
        counter += fadeAmount;
        if (counter <= 0 || counter >= 255)
        {
            fadeAmount = -fadeAmount;
        }
        MTIMER_vOutputFastPWM(TIMER_CHANNEL_0, counter);
        // MTIMER_vOutputPhaseCorrectPWM(TIMER_CHANNEL_0, counter);
        MTIMER_vDelayMS(TIMER_CHANNEL_2, 50);
    }
}
References GPIO_PIN3, GPIO_PORTB, MGPIO_vSetPinDirection(), MTIMER_vDelayMS(), MTIMER_vOutputFastPWM(), OUTPUT, TIMER_CHANNEL_0, TIMER_CHANNEL_2, and TRUE.
Referenced by vAPPS_main().